'use strict';

const Incident = require('../models/Incident.model');
const logger = require('../config/logger');

const BF_TTL = 900;
const BF_LIMIT = 5;

const bruteForceIncrement = async (ip, app) => {
  try {
    const redis = require('../config/redis');
    const key = `bf:${ip}`;
    const count = await redis.incr(key);
    await redis.expire(key, BF_TTL);

    if (count >= BF_LIMIT) {
      await redis.set(`blocked:${ip}`, 1, 'EX', BF_TTL);

      await Incident.create({
        title: `Brute force detected from ${ip}`,
        type: 'brute_force',
        severity: 'high',
        isAutoGenerated: true,
        affectedSystem: ip,
      });

      const io = app?.get('io');
      if (io) {
        io.to('admin').emit('threat:detected', {
          type: 'brute_force',
          ip,
          timestamp: new Date().toISOString(),
        });
      }
    }
  } catch (err) {
    logger.error({ err }, 'bruteForceIncrement failed');
  }
};

const clearBruteForce = async (ip) => {
  try {
    const redis = require('../config/redis');
    await redis.del(`bf:${ip}`);
  } catch (err) {
    logger.error({ err }, 'clearBruteForce failed');
  }
};

module.exports = { bruteForceIncrement, clearBruteForce };
